# "featureName" property - name of the feature
featureName=Teamcenter Business Modeler IDE

# "providerName" property - name of the company that provides the feature
providerName=Siemens PLM Software, Inc.

# "description" property - description of the feature
featureDescription=Teamcenter Business Modeler IDE

# "copyright" property - text of the "Feature Update Copyright"
featureCopyright=\
Siemens and the Siemens logo are registered trademarks of Siemens AG. Teamcenter \
is a registered trademark of Siemens Product Lifecycle Management Software Inc. \
This software and related documentation are proprietary to Siemens Product \
Lifecycle Management Software Inc.\n\
© 2021 Siemens Product Lifecycle Management Software Inc.\n\
\n\
All rights reserved.\n\
\n\n\
SwarmStream(tm) Technology © 2006 Onion Networks, Inc.  All Rights Reserved.

# "license" property
featureLicense=Teamcenter Business Modeler IDE is subject to the same terms and conditions governing your use of Teamcenter 12.

# "licenseURL" property - URL of the "Feature License"
# do not translate value - just change to point to a locale-specific HTML page
licenseURL=license.html
