#Product Runtime Configuration File

# Default Eclipse configuration
org.eclipse.update.reconcile=false
eclipse.p2.profile=SDKProfile
osgi.framework=file\:plugins/org.eclipse.osgi_3.18.100.v20220817-1601.jar
equinox.use.ds=true
eclipse.buildId=4.25.0.I20220831-1800
osgi.bundles=reference\:file\:org.eclipse.equinox.simpleconfigurator_1.4.100.v20220620-1617.jar@1\:start
org.eclipse.equinox.simpleconfigurator.configUrl=file\:org.eclipse.equinox.simpleconfigurator/bundles.info
osgi.framework.extensions=
osgi.bundles.defaultStartLevel=4
eclipse.p2.data.area=@config.dir/../p2/

# BMIDE specific configuration
osgi.splashPath=platform\:/base/plugins/com.teamcenter.bmide.branding_2406.jar
eclipse.product=com.teamcenter.bmide.branding.product
osgi.configuration.area=@user.dir/../workspace/config
org.eclipse.ui/defaultPerspectiveId=com.teamcenter.bmide.server.ui.perspective.novice
osgi.instance.area.default=@user.dir/../workspace/2406000.0.0
osgi.user.area=@user.dir/../workspace/2406000.0.0
osgi.locking=none
org.eclipse.help.base/activeHelp=false